### ISSUE TITLE
env() 関数の注意書きの文章が変更されていない(「null を返す」→「システムレベルの環境変数値を返す」)

### ISSUE THREAD

**Issue by kawahara-kunio** [laravel-ja/ja-docs-10.x#14]
下記の「Warning!! 」の部分の文章について、古い文章のままのように見受けられます。

https://readouble.com/laravel/10.x/ja/helpers.html?header=env()
>Warning!! 開発期間中にconfig:cacheコマンドを実行する場合は、設定ファイルの中で必ずenv関数だけを使用してください。設定ファイルがキャッシュされると、.envファイルはロードされなくなり、env関数の呼び出しはすべてnullを返します。

![スクリーンショット 2023-05-22 15 15 11](https://github.com/laravel-ja/ja-docs-10.x/assets/18457673/fd4edf98-784d-4c28-9d0e-dc003e75b192)

本家は、Ver.8において、下記のように変更されています。
(「null を返す」から「システムレベルの環境変数値を返す」という意図の文章に変更されている)

https://laravel.com/docs/7.x/configuration#configuration-caching
>Once the configuration has been cached, the .env file will not be loaded and all calls to the env function will return null.

https://laravel.com/docs/8.x/configuration#configuration-caching
>Once the configuration has been cached, the .env file will not be loaded; therefore, the env function will only return external, system level environment variables.

**Comment by HiroKws** [comment]
恐れ入りますが、どのバージョンのお話でしょうか。
こちらはバージョン10のリポジトリです。確認しましたが、バージョン１０の原文は、翻訳どおりで、NULLを返すとなっています。
readouble.comで古いバージョンの情報を当時のまま保持しているのは、参照される側のバージョンと合うようにという意図で残しています。そのためURLにバージョンを含めています。

**Comment by HiroKws** [comment]
https://readouble.com/laravel/10.x/ja/configuration.html

わかりました。設定のキャッシュの説明と、ヘルパのenv関数の説明を混ぜていらっしゃるようです。
私は原文をそのまま日本語に訳しています。ですから、内容に間違いがあっても、紛らわしくても、そのまま訳しています。翻訳のレベルで訂正を入れてしまうと管理が非常に煩雑になるからです。（昔はやっていました。）READMEを参照ください。

もし、間違いを見つけたら、原文に対して修正の依頼を出してください。

**Comment by kawahara-kunio** [comment]
なるほど、理解しました。
比較する場所を間違えていました(設定のキャッシュの説明と、ヘルパのenv関数の説明が似た文章だったので、同じ箇所と誤解していました)。
翻訳の方針についても理解しました(個人的には、方針に違和感は無いです)。

回答ありがとうございました。
