### ISSUE TITLE
表示崩れ

### ISSUE THREAD

**Issue by s-ike** [laravel-ja/ja-docs-10.x#18]
Laravel 10.x ヘルパ ページ
https://readouble.com/laravel/10.x/ja/helpers.html

以下のようにURL以下の表示が崩れているように見えます。
![image](https://github.com/laravel-ja/ja-docs-10.x/assets/13024418/8f3655f2-332c-4636-8a41-7a4c2ba526ec)

## 環境

以下の環境で確認しています

- m1 macOS 13.5.2（22G91） / FireFox 117.0.1 (64 ビット)
- m1 macOS 13.5.2（22G91） /  Arc Version 1.9.1 (41815) Chromium Engine Version 117.0.5938.88 ←スクショした環境
- intel macOS 13.3.1（22E261） / Vivaldi | 6.2.3105.45 (Stable channel) （x86_64）

**Comment by HiroKws** [comment]
ありがとうございます。
原因はオリジナルの英語版で</div>がダブっているためでした。
搭載とのメンテナンス方針で、日本語版は英語版と行単位に構造を合わせているため、当サイトで直接修正しません。
後ほど、本家へ修正のプルリクを送っておきます。そちらが修正されるまで、辛抱ください。

**Comment by HiroKws** [comment]
本家へ修正のプルリクを送りました。

**Comment by HiroKws** [comment]
本家で取り込まれたため、反映しました。

https://github.com/laravel/docs/pull/9047#event-10456387890
