### ISSUE TITLE
リンク切れについて

### ISSUE THREAD

**Issue by PRiMENON** [laravel-ja/ja-docs-10.x#19]
はじめてまして。

拝見していたところ、リンク切れを見つけましたので報告します。

## Laravel 10.x 暗号化
[Laravel 10.x 暗号化](https://readouble.com/laravel/10.x/ja/encryption.html)の見出し「設定」

> 通常、APP_KEY環境変数の値は、__Laravelのインストール__ 中に生成されます。

リンク先
`https://readouble.com/laravel/10.x/ja/%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB.html` 

正しくは、`https://readouble.com/laravel/10.x/ja/installation.html` ではないでしょうか。

## 左上の本アイコンの中にあるAPIドキュメント

リンク先
`https://laravel.com/api/- [API Documentation](10.x`

正しくは、`https://laravel.com/api/10.x/` ではないでしょうか。

**Comment by HiroKws** [comment]
ありがとうございます。修正しました。
