### ISSUE TITLE
脱字報告

### ISSUE THREAD

**Issue by nomi3** [laravel-ja/ja-docs-10.x#2]
https://readouble.com/laravel/10.x/ja/http-tests.html
現状: Laravelは、HTTPテスト中にセッションを操作ためヘルパをいくつか提供しています。
修正: Laravelは、HTTPテスト中にセッションを操作するためのヘルパをいくつか提供しています。

**Comment by HiroKws** [comment]
ありがとうございます。

**Comment by nomi3** [comment]
ご確認頂き誠にありがとうございます！
