### ISSUE TITLE
リンク切れ報告

### ISSUE THREAD

**Issue by po-kun** [laravel-ja/ja-docs-10.x#20]
リンク切れがありましたので、報告します。

### ページ（章）
https://readouble.com/laravel/10.x/ja/lifecycle.html
章 : サービスプロバイダ

### リンク切れ箇所

> アプリケーションの[サービスプロバイダ](https://readouble.com/laravel/10.x/ja/provider.html)をロードすることです。

こちらのリンク先が現状下記となっていて、404になります
https://readouble.com/laravel/10.x/ja/provider.html

こちらが正しいかと思います。
https://readouble.com/laravel/10.x/ja/providers.html

**Comment by HiroKws** [comment]
ありがとうございました。修正しました。
