### ISSUE TITLE
Laravel Scoutページのタイポ

### ISSUE THREAD

**Issue by KenyaMasuko** [laravel-ja/ja-docs-10.x#27]
いつも本当にありがとうございます！

## 概要
Laravel Scoutのページでタイポと思われるものを見つけましたので下記に詳細を記します。

## 詳細
https://readouble.com/laravel/10.x/ja/scout.html でタイポを見つけました。
内容としては 正しくは`Scout`であろうと思われる箇所が`Scou`となっていました。
![image](https://github.com/laravel-ja/ja-docs-10.x/assets/85816730/73e2e1d7-c923-4f99-9417-b5650005ce9b)

ご確認のほどよろしくお願いいたします。

**Comment by HiroKws** [comment]
ありがとうございました。修正いたしました。
