### ISSUE TITLE
サポートポリシーの表がうまく表示されていません

### ISSUE THREAD

**Issue by crhg** [laravel-ja/ja-docs-10.x#3]
https://readouble.com/laravel/10.x/ja/releases.html#support-policy
の表が以下のようになっています。
Macのsafariとwindowsのfirefoxで試しましたがどちらも同様でした。

<img width="876" alt="スクリーンショット 2023-03-22 14 41 04" src="https://user-images.githubusercontent.com/8174597/226812946-fc25d2e4-4b09-477d-946b-a228b86c9205.png">

**Comment by HiroKws** [comment]
ありがとうございます。
同様の現象が、他のページでも見つかりました。
原文にHTMLタグのdivがテーブルを使用しているところに追加され、div要素の内側の内容をMarkdownからHTMLへの変換に使用しているpandocがそのまま書き出す仕様であるために発生した不具合のようです。
Markdownはしっかりと仕様が決まっているドキュメント形式ではないため、pandocのバグだと言えませんので、こちらの変換スクリプトで対応します。しばらくお待ち下さい。

**Comment by HiroKws** [comment]
生成スクリプトで、新しく追加された要素を削除し、全ページを生成し直しました。
